### ISSUE TITLE
Support Pipelines

### ISSUE THREAD

**Issue by xorz57** [xorz57/shell#1]
Read more about Pipelines [here](https://www.gnu.org/software/bash/manual/html_node/Pipelines.html#Pipelines).

**Comment by BuzzHari** [comment]
Hey! I would like to add this feature.

**Comment by xorz57** [comment]
@BuzzHari sure! Go ahead!

**Comment by xorz57** [comment]
@all-contributors please add @BuzzHari  for his code.

**Comment by xorz57** [comment]
@all-contributors please add @xorz57 for his code.
