### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by xorz57** [xorz57/shell#15]
@BuzzHari would you like to help me refactor `parse.c`, `command.c` and `command_table.c`?

**Comment by swarupe** [comment]
What changes required for these files?

**Comment by xorz57** [comment]
@swarupe Just code cleanup. Splitting the code in multiple files and multiple functions. I want less code in `parse.c`.

**Comment by BuzzHari** [comment]
@xorz57 I am going a bit busy these days. Meanwhile if @swarupe wants a go at it, that'll be cool.

**Comment by xorz57** [comment]
@BuzzHari Yeah, sure!

**Comment by xorz57** [comment]
@swarupe make sure to use `valgrind` after every compilation to see if there are any `memory leaks`/`memory errors`.
